version: 2
jobs:
  build:
    working_directory: ~/bko-java/src/main/java

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout:
          path: ~/bko-java

      - run:
          name: Build
          command: javac interview/Interview.java

      - run:
          name: Test
          command: java interview.Interview